/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import ame.potrero;
import ame.rotacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Camilo
 */
public class controlTierras extends javax.swing.JFrame {

    ArrayList<rotacion> rotaciones = new ArrayList<rotacion>();
    ArrayList<potrero> potreros = new ArrayList<potrero>();
    String nombreR, nombrepo;
    Double tamanoRotacion, tamano;
    int numeroPotreros;
    rotacion rots = new rotacion();
    potrero pots = new potrero();
    int no = 0;
    String consultar;

    public controlTierras() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void llenaRot() {
        rotaciones = rots.getRot();
    }
    
    public void llenaPotre(){
        potreros = pots.getPot();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desea = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1FlechaAtras = new javax.swing.JLabel();
        ConsulPotre = new javax.swing.JButton();
        RegisRota = new javax.swing.JButton();
        ConsulRota = new javax.swing.JButton();
        RegisPotre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Desea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Desea.setForeground(new java.awt.Color(255, 255, 255));
        Desea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Desea.setText("¿Qué desea hacer?");
        getContentPane().add(Desea, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 460, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Titulo.setText("CONTROL DE TIERRAS");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Picture4_1.png"))); // NOI18N

        jLabel1FlechaAtras.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1FlechaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Picture4.png"))); // NOI18N
        jLabel1FlechaAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1FlechaAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1FlechaAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1Titulo)
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jLabel1FlechaAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 360, 530));

        ConsulPotre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConsulPotre.setText("Consultar Potrero");
        ConsulPotre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulPotreActionPerformed(evt);
            }
        });
        getContentPane().add(ConsulPotre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 180, 50));

        RegisRota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegisRota.setText("Registrar Rotación");
        RegisRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisRotaActionPerformed(evt);
            }
        });
        getContentPane().add(RegisRota, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 180, 50));

        ConsulRota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConsulRota.setText("Consultar Rotación");
        ConsulRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulRotaActionPerformed(evt);
            }
        });
        getContentPane().add(ConsulRota, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 50));

        RegisPotre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegisPotre.setText("Registrar Potrero");
        RegisPotre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisPotreActionPerformed(evt);
            }
        });
        getContentPane().add(RegisPotre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 460, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FlechaAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1FlechaAtrasMouseClicked
        menuJefe mF = new menuJefe();
        mF.show();
        dispose();
    }//GEN-LAST:event_jLabel1FlechaAtrasMouseClicked

    private void RegisPotreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisPotreActionPerformed
        llenaPotre();
        nombrepo = JOptionPane.showInputDialog("Ingrese el nombre del potrero que agregará");
        tamano = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el tamaño del potrero"));
        potreros.add(new potrero(nombrepo, tamano));
    }//GEN-LAST:event_RegisPotreActionPerformed

    private void RegisRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisRotaActionPerformed
        llenaRot();
        nombreR = JOptionPane.showInputDialog("Ingrese el nombre de la rotación que agregará");
        tamanoRotacion = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el tamaño de la rotación"));
        numeroPotreros = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de potreros en la rotación"));
        rotaciones.add(new rotacion(nombreR, numeroPotreros, tamanoRotacion));
        JOptionPane.showMessageDialog(null, "La rotación: " + rotaciones.get(rotaciones.size() - 1).getNombre() + " fué añadida");

    }//GEN-LAST:event_RegisRotaActionPerformed

    private void ConsulRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulRotaActionPerformed
        // TODO add your handling code here:
        consultar = JOptionPane.showInputDialog("La finca cuenta con " + rotaciones.size() + " rotaciones.\n¿Cual desea consultar?");
        for (rotacion r : rotaciones) {
            no = no + 1;

            if (r.getNombre().equals(consultar)) {
                JOptionPane.showMessageDialog(null, "Esta rotación cuenta con " + r.getNumeroPotreros() + " potreros Y tiene un tamaño de " + r.getTamanoRotacion() + " hectáreas");
                no = 0;
                break;
            } 

        }
        if (no == rotaciones.size()) {
            JOptionPane.showMessageDialog(null, "Esa rotacion no existe");
        }


    }//GEN-LAST:event_ConsulRotaActionPerformed

    private void ConsulPotreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulPotreActionPerformed
       consultar = JOptionPane.showInputDialog("¿Qué potrero desea consultar?");
       no = 0;
       for (potrero pott : potreros){
           no = no + 1;
           if(pott.getNombrepo().equals(consultar)){
               JOptionPane.showMessageDialog(null, "Este potrero tiene un tamaño de " + pott.getTamano() + " hectáreas");
               no = 0;
               break;
           }
       }
       if(no == potreros.size()){
           JOptionPane.showMessageDialog(null, "Ese potrero no existe");
       }
    }//GEN-LAST:event_ConsulPotreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlTierras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlTierras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlTierras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlTierras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controlTierras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsulPotre;
    private javax.swing.JButton ConsulRota;
    private javax.swing.JLabel Desea;
    private javax.swing.JButton RegisPotre;
    private javax.swing.JButton RegisRota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1FlechaAtras;
    private javax.swing.JLabel jLabel1Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
