/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import ame.usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Camilo
 */
public class controlUsuarios extends javax.swing.JFrame {

    String consultar;
    ArrayList<usuario> usuarios = new ArrayList<usuario>();
    usuario user = new usuario();
    int no;
    

    public controlUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void llenaUs() {
        usuarios = user.getUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1User = new javax.swing.JLabel();
        jLabel1Titulo = new javax.swing.JLabel();
        jLabel2Aca = new javax.swing.JLabel();
        jLabel1FlechaAtras = new javax.swing.JLabel();
        ConsulUsu = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Webp.net-resizeimage.png"))); // NOI18N
        getContentPane().add(jLabel1User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 450, 160));

        jLabel1Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Titulo.setText("CONTROL DE USUARIOS");
        getContentPane().add(jLabel1Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, -1));

        jLabel2Aca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2Aca.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2Aca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Aca.setText("Aquí puede consultar los usuarios que existen");
        getContentPane().add(jLabel2Aca, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 270, 460, -1));

        jLabel1FlechaAtras.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1FlechaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Picture4.png"))); // NOI18N
        jLabel1FlechaAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1FlechaAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1FlechaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        ConsulUsu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConsulUsu.setText("Consultar Usuarios");
        ConsulUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulUsuActionPerformed(evt);
            }
        });
        getContentPane().add(ConsulUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 180, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FlechaAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1FlechaAtrasMouseClicked
        menuJefe mF = new menuJefe();
        mF.show();
        dispose();
    }//GEN-LAST:event_jLabel1FlechaAtrasMouseClicked

    private void ConsulUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulUsuActionPerformed
        llenaUs();        
        consultar = JOptionPane.showInputDialog("¿Ingrese el nombre del usuario que desea consultar?");
        for (usuario r : usuarios) {
            no = no + 1;

            if (r.getNombre().equals(consultar)) {
                JOptionPane.showMessageDialog(null, "El usuario " + consultar + 
                        ", de apellido " + r.getApellido() + " se encuentra "
                                + "trabajando en la posición de " + r.getTipoUsuario());
                no = 0;
                break;
            }

        }
        if (no == usuarios.size()) {
            JOptionPane.showMessageDialog(null, "Ese usuario no existe");
        }
    }//GEN-LAST:event_ConsulUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controlUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsulUsu;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel jLabel1FlechaAtras;
    private javax.swing.JLabel jLabel1Titulo;
    private javax.swing.JLabel jLabel1User;
    private javax.swing.JLabel jLabel2Aca;
    // End of variables declaration//GEN-END:variables
}
