/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;


import ame.animal;
import ame.rotacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Camilo
 */
public class controlAnimales extends javax.swing.JFrame {

    private static ArrayList<animal> animales = new ArrayList<animal>();
    animal aN = new animal();
    String identificacion, estado, genero, madre, consultar;
    int dia, mes, ano, aceptar, index, no;
    boolean vacio;

    public controlAnimales() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void llenaAnim() {
        animales = aN.getAnimales();
    }

    public void deterMadre(String madre) {
        if (vacio == true) {
            JOptionPane.showMessageDialog(null, "Este es el primer animal de su lista");
            animales.add(new animal(identificacion, madre, estado, mes, ano, dia, genero));
            aceptar = 1;
        } else if (madre.equals("compra")) {
            JOptionPane.showMessageDialog(null, "Es un animal comprado, desconocemos a su madre y lo añadimos a la lista");
            animales.add(new animal(identificacion, madre, estado, mes, ano, dia, genero));
            index = animales.size();
            aceptar = 1;
        } else {
            index = animales.size();
            JOptionPane.showMessageDialog(null, "No es un animal comprado, tiene madre. Buscaré si la madre existe");
            for (int i = 0; i <= index; i++) {
                if (madre.equals(animales.get(i).getIdentificacion())) {
                    System.out.println("La madre existe");
                    System.out.println(animales.get(i).getIdentificacion());
                    animales.add(new animal(identificacion, madre, estado, mes, ano, dia, genero));
                    aceptar = 1;
                    return;
                } else if (index - 1 == i) {
                    JOptionPane.showMessageDialog(null, "El animal madre, identificado como '" + madre + "', no presenta registro alguno. Por favor, vuelva a intentar");
                    aceptar = 0;
                    return;
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1FlechaAtras = new javax.swing.JLabel();
        RegisAnimal = new javax.swing.JButton();
        ConsulAnimal = new javax.swing.JButton();
        Desea = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Titulo.setText("CONTROL DE ANIMALES");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ddddddd.png"))); // NOI18N

        jLabel1FlechaAtras.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1FlechaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Picture4.png"))); // NOI18N
        jLabel1FlechaAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1FlechaAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1FlechaAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1Titulo)
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jLabel1FlechaAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 360, 530));

        RegisAnimal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegisAnimal.setText("Registrar Animal");
        RegisAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(RegisAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 180, 50));

        ConsulAnimal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConsulAnimal.setText("Consultar Animal");
        ConsulAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(ConsulAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 180, 50));

        Desea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Desea.setForeground(new java.awt.Color(255, 255, 255));
        Desea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Desea.setText("¿Qué desea hacer?");
        getContentPane().add(Desea, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 460, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 460, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FlechaAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1FlechaAtrasMouseClicked
        menuJefe mF = new menuJefe();
        mF.show();
        dispose();
    }//GEN-LAST:event_jLabel1FlechaAtrasMouseClicked

    private void RegisAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisAnimalActionPerformed
        llenaAnim();
        identificacion = JOptionPane.showInputDialog("Ingrese la identificación del animal");
        estado = JOptionPane.showInputDialog("Ingrese el estado del animal (Ok, preñado, enfermo, muerto)");
        dia = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el dia de nacimiento"));
        mes = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el mes de nacimiento"));
        ano = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el año de nacimiento"));
        genero = JOptionPane.showInputDialog("Ingrese el género (F o M)");

        vacio = animales.isEmpty();
        do {
            madre = JOptionPane.showInputDialog("Ingrese la identificación de la madre del animal. Si el animal fue comprado, por favor escriba 'compra'");
            deterMadre(madre);
        } while (aceptar == 0);
        aceptar = 0;
        vacio = animales.isEmpty();
        if (vacio == false) {
            JOptionPane.showMessageDialog(null, "El animal: " + animales.get(animales.size() - 1).getIdentificacion() + " fué añadido");
        }
    }//GEN-LAST:event_RegisAnimalActionPerformed

    private void ConsulAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulAnimalActionPerformed
        consultar = JOptionPane.showInputDialog("¿Qué animal desea consultar?");
        for (animal r : animales) {
            no = no + 1;

            if (r.getIdentificacion().equals(consultar)) {
                JOptionPane.showMessageDialog(null, "Este animal tiene una edad de " +r.calculoEdad()+ " años, es hijo/a de " + r.getMadre() + " y es de género " + r.getGenero());
                no = 0;
                break;
            } 

        }
        if (no == animales.size()) {
            JOptionPane.showMessageDialog(null, "Ese animal no existe");
        }


    }//GEN-LAST:event_ConsulAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controlAnimales().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsulAnimal;
    private javax.swing.JLabel Desea;
    private javax.swing.JButton RegisAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1FlechaAtras;
    private javax.swing.JLabel jLabel1Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
