/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import ame.usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Camilo
 */
public class Login extends javax.swing.JFrame {

    //Atributos
    int no = 0;
    usuario user = new usuario();
    ArrayList<usuario> usuarios = new ArrayList<usuario>();
    String nombre, apellido, contrasena, tipoUsuario;

    public void llenaUs() {
        usuarios = user.getUsuarios();
    }

    public void setUsuarios(String nombre, String apellido, String contrasena, String tipoUsuario) {
        usuarios.add(new usuario(nombre, apellido, contrasena, tipoUsuario));
    }

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextField1IngresoUsuario1.setBackground(new java.awt.Color(0, 0, 0, 1));
        jTextField1IngresoContrasena.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Salir = new javax.swing.JLabel();
        jLabel1User = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1IngresoContrasena = new javax.swing.JTextField();
        jTextField1IngresoUsuario1 = new javax.swing.JTextField();
        jLabel1Titulo = new javax.swing.JLabel();
        jLabel2SinUsuario = new javax.swing.JLabel();
        jLabel2Aca = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1IngresarSistema = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Salir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1Salir.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Salir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1Salir.setText("X");
        jLabel1Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1SalirMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 420, -1));

        jLabel1User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Webp.net-resizeimage.png"))); // NOI18N
        getContentPane().add(jLabel1User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 450, 160));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 200, 20));

        jTextField1IngresoContrasena.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1IngresoContrasena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1IngresoContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1IngresoContrasena.setText("Contraseña");
        jTextField1IngresoContrasena.setBorder(null);
        jTextField1IngresoContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1IngresoContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1IngresoContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 200, 30));

        jTextField1IngresoUsuario1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1IngresoUsuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1IngresoUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1IngresoUsuario1.setText("Usuario");
        jTextField1IngresoUsuario1.setBorder(null);
        jTextField1IngresoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1IngresoUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1IngresoUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 200, 30));

        jLabel1Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Titulo.setText("INGRESO AL SISTEMA");
        getContentPane().add(jLabel1Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 450, -1));

        jLabel2SinUsuario.setFont(new java.awt.Font("Segoe UI Black", 3, 13)); // NOI18N
        jLabel2SinUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2SinUsuario.setText("Registrese acá");
        jLabel2SinUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2SinUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2SinUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, 40));

        jLabel2Aca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2Aca.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2Aca.setText("¿Nuevo usuario?");
        getContentPane().add(jLabel2Aca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 200, 10));

        jButton1IngresarSistema.setBackground(new java.awt.Color(0, 102, 102));
        jButton1IngresarSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1IngresarSistema.setText("Ingresar");
        jButton1IngresarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IngresarSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1IngresarSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 130, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1SalirMouseClicked

    private void jTextField1IngresoContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1IngresoContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1IngresoContrasenaActionPerformed

    private void jTextField1IngresoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1IngresoUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1IngresoUsuario1ActionPerformed

    private void jLabel2SinUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2SinUsuarioMouseClicked
        RegistroUsuario RU = new RegistroUsuario();
        RU.show();
        dispose();
    }//GEN-LAST:event_jLabel2SinUsuarioMouseClicked

    private void jButton1IngresarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IngresarSistemaActionPerformed
        //Ingreso de usuario
        //https://pharos.sh/leer-y-escribir-csv-en-java/
        nombre = jTextField1IngresoUsuario1.getText();
        contrasena = jTextField1IngresoContrasena.getText();

        for (usuario u : usuarios) {
            no = no + 1;
            if (u.getNombre().equals(nombre) && u.getContraseña().equals(contrasena)) {
                JOptionPane.showMessageDialog(null, "Usuario encontrado.");
                JOptionPane.showMessageDialog(null, "Accediendo a módulo de: "
                        + "" + u.getTipoUsuario());
                if (u.getTipoUsuario().equals("Jefe")) {
                    //JOptionPane.showMessageDialog(null, "Este es el modulo de jefe");
                    menuJefe mJ = new menuJefe();
                    mJ.show();
                    dispose();
                } else if (u.getTipoUsuario().equals("Empleado")) {
                    //JOptionPane.showMessageDialog(null, "Modulo de empleado");
                    menuEmpleado mE = new menuEmpleado();
                    mE.show();
                    dispose();
                }
                break;

            } else if (no == usuarios.size()) {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña no válidos");
            }
        }

        //for(usuario u: usuarios){
        //    JOptionPane.showMessageDialog(null, "Nombre usuario: " + u.getNombre());
        //}

    }//GEN-LAST:event_jButton1IngresarSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButton1IngresarSistema;
    private javax.swing.JLabel jLabel1Salir;
    private javax.swing.JLabel jLabel1Titulo;
    private javax.swing.JLabel jLabel1User;
    private javax.swing.JLabel jLabel2Aca;
    private javax.swing.JLabel jLabel2SinUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1IngresoContrasena;
    private javax.swing.JTextField jTextField1IngresoUsuario1;
    // End of variables declaration//GEN-END:variables
}
