/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JLabel;

/**
 *
 * @author Juan Camilo
 */
public class menuJefe extends javax.swing.JFrame {

    public menuJefe() {

        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Titulo = new javax.swing.JLabel();
        jLabel2Aca = new javax.swing.JLabel();
        Usuarios = new javax.swing.JButton();
        Animales = new javax.swing.JButton();
        Tierras = new javax.swing.JButton();
        Aforos = new javax.swing.JButton();
        Salir = new javax.swing.JLabel();
        jLabel1FlechaAtras = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Titulo.setText("INGRESO AL SISTEMA");
        getContentPane().add(jLabel1Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 350, -1));

        jLabel2Aca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2Aca.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2Aca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Aca.setText("Por favor, elija una opción");
        getContentPane().add(jLabel2Aca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 350, -1));

        Usuarios.setText("CONTROL DE USUARIOS");
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 190, 50));

        Animales.setText("CONTROL DE ANIMALES");
        Animales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalesActionPerformed(evt);
            }
        });
        getContentPane().add(Animales, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 190, 50));

        Tierras.setText("CONTROL DE TIERRAS");
        Tierras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TierrasActionPerformed(evt);
            }
        });
        getContentPane().add(Tierras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 190, 50));

        Aforos.setText("CONTROL DE AFOROS");
        Aforos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AforosActionPerformed(evt);
            }
        });
        getContentPane().add(Aforos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 190, 50));

        Salir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Salir.setText("X");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 330, -1));

        jLabel1FlechaAtras.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1FlechaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Picture4.png"))); // NOI18N
        jLabel1FlechaAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1FlechaAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1FlechaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 50, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back2.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 498));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        controlUsuarios cU = new controlUsuarios();
        cU.show();
        dispose();
    }//GEN-LAST:event_UsuariosActionPerformed

    private void AnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalesActionPerformed
        // TODO add your handling code here:
        controlAnimales cA =  new controlAnimales();
        cA.show();
        dispose();
    }//GEN-LAST:event_AnimalesActionPerformed

    private void TierrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TierrasActionPerformed
        // TODO add your handling code here:
        controlTierras cT = new controlTierras();
        cT.show();
        dispose();
    }//GEN-LAST:event_TierrasActionPerformed

    private void AforosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AforosActionPerformed
        ControlAforos aF = new ControlAforos();
        aF.show();
        dispose();
    }//GEN-LAST:event_AforosActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void jLabel1FlechaAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1FlechaAtrasMouseClicked
        Login LI = new Login();
        LI.show();
        dispose();
    }//GEN-LAST:event_jLabel1FlechaAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuJefe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aforos;
    private javax.swing.JButton Animales;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Salir;
    private javax.swing.JButton Tierras;
    private javax.swing.JButton Usuarios;
    private javax.swing.JLabel jLabel1FlechaAtras;
    private javax.swing.JLabel jLabel1Titulo;
    private javax.swing.JLabel jLabel2Aca;
    // End of variables declaration//GEN-END:variables
}
